config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :edit, :update, :show]
  patch 'become_admin' => 'users#become_admin', :as => :become_admin

  resources :materials, except: :show do
    get :material_logs, to: 'material_logs#show'
  end

  get :material_logs, to: 'material_logs#index'


  resources :home, only: :index
  root to: 'home#index', :as => :root_app
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/material.rb
class Material < ApplicationRecord
  attr_accessor :quantity_entrance, :quantity_exit

  belongs_to :user, optional: true
  has_many :material_logs

  validates_uniqueness_of :name
  validates_numericality_of :quantity
  validates :quantity, numericality: {:greater_than => 0}, on: :create

  before_update :have_stock_for_pick_up?

  private

  def have_stock_for_pick_up?
    return if quantity_exit.blank? || quantity_entrance.present?

    material = Material.find_by(name: name)
    total = material.quantity - quantity_exit.to_i

    return if total.positive? || total == 0

    errors.add :base, "Retirada mais do que existe no estoque."

    throw(:abort)
  end
end

app/models/material_log.rb
class MaterialLog < ApplicationRecord
  belongs_to :material
  belongs_to :user

  enum status: [:entrance, :exit]

  def translate_status
    # ideal é usar o arquivo pt-br para traduzir enum no rails
    return 'entrada' if entrance?
    return 'saída' if exit?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :materials

  enum role: [:usuario, :suporte, :administrador]

  scope :active, -> {where(active: true)}
  scope :inactive, -> {where(active: false)}

  before_destroy :impossible_destroy_user

  def full_name
    return if first_name.blank? || last_name.blank?

    [first_name, last_name].compact.join(' ')
  end

  def become_admin
    if User.all.count == 1 && !administrador?
      update(role: 'administrador')
    end
  end

  def translate_status
    return 'Ativo' if active
    return 'Inativo' if inactive
  end


  def active_for_authentication?
    super && active
  end

  def inactive_message
    "Sorry, this account has been deactivated."
  end

  private

  def impossible_destroy_user
    errors.add :base, "Impossível destruir usuário"

    throw(:abort)
  end
end

app/models/validations/user.rb
module Validations
  module User
    extend ActiveSupport::Concern
    
    included do
      has_secure_password
      validates name, presence: true, length: {maximum: 50}
      validates password, presence: true, length: {minimum: 6}
      VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
      validates email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
      before_save { self.email = email.downcase }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @materials = Material.all
    @users = User.all
    @logs = MaterialLog.all
  end
end

app/controllers/material_logs_controller.rb
class MaterialLogsController < ApplicationController
  def index
    @logs = MaterialLog.all
  end

  def show
    @logs = Material.find(params[:material_id]).material_logs
  end
end

app/controllers/materials_controller.rb
# frozen_string_literal: true

class MaterialsController < ApplicationController
  before_action :load_material, only: [:update, :edit, :destroy]

  def index
    @materials = Material.all
  end

  def new
    @material = Material.new
  end

  def create
    @material = Material.new(material_params)
    @material.user = current_user
    @material.quantity = total

    if @material.save
      redirect_to materials_path, notice: "Entrada de material #{@material.name}, feita com sucesso."
    else
      render :new, alert: 'Ocorreu um erro. Tente novamente!'
    end
  end

  def edit; end

  def update
    if !business_hours_available? && quantity_exit.present?
      flash.now[:alert] = 'Fora do horário comercial para retirada de estoque!'
      return render :edit
    elsif @material.update(material_params)
      redirect_to materials_path, notice: "Material #{@material.name}, atualizado com sucesso."

      create_logs
      calculate_new_quantity
    else
      render :edit, alert: 'Ocorreu um erro ao atualizar material, verifique seu estoque!'
    end
  end

  def destroy
    if material_with_logs?
      return redirect_to materials_path, notice: 'O material já tem logs.'
    else
      @material.destroy
      redirect_to materials_path, notice: 'O material foi excluído com sucesso.'
    end
  end

  private

  def load_material
    @material = Material.find(params[:id])
  end

  def total
    return quantity_entrance if quantity_entrance.present?
    return quantity_exit if quantity_exit.present?
  end

  def create_logs
    if quantity_exit.present?
      Services::Material::MaterialLogService.new(@material, quantity_entrance, quantity_exit).material_exit
    end

    if quantity_entrance.present?
      Services::Material::MaterialLogService.new(@material, quantity_entrance, quantity_exit).material_entrance
    end
  end

  def calculate_new_quantity
    if quantity_exit.present?
      Services::Material::CalculateQuantityService.new(@material, quantity_entrance, quantity_exit).negative
    end

    if quantity_entrance.present?
      Services::Material::CalculateQuantityService.new(@material, quantity_entrance, quantity_exit).positive
    end
  end

  def quantity_entrance
    params[:material][:quantity_entrance]
  end

  def quantity_exit
    params[:material][:quantity_exit]
  end

  def material_with_logs?
    @material.material_log.present?
  end

  def business_hours_available?
    business_range_hour = 9..18

    Date.today.on_weekday? && business_range_hour.include?(DateTime.now.hour)
  end

  def material_params
    params.required(:material).permit(:name, :quantity_entrance, :quantity_exit, :user_id)
  end
end

app/controllers/services/material/calculate_quantity_service.rb
module Services
  module Material
    class CalculateQuantityService
      def initialize(material, quantity_entrance, quantity_exit)
        @material = material
        @quantity_entrance = quantity_entrance
        @quantity_exit = quantity_exit
      end

      def negative
        material = ::Material.find_by(name: @material.name)
        material.update(quantity: material.quantity - @quantity_exit.to_i)
      end

      def positive
        material = ::Material.find_by(name: @material.name)
        material.update(quantity: material.quantity + @quantity_entrance.to_i)
      end
    end
  end
end

app/controllers/services/material/material_log_service.rb
module Services
  module Material
    class MaterialLogService
      def initialize(material, quantity_entrance, quantity_exit)
        @material = material
        @quantity_entrance = quantity_entrance
        @quantity_exit = quantity_exit
      end

      def material_exit
        material_log = ::MaterialLog.new(user: @material.user, material: @material, quantity: @quantity_exit.to_i, status: 'exit')
        material_log.save
      end

      def material_entrance
        material_log = ::MaterialLog.new(user: @material.user, material: @material, quantity: @quantity_entrance.to_i, status: 'entrance')
        material_log.save
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:edit, :update]

  def index
    @users = User.all if current_user.administrador?

    @users = User.all.active
  end

  def edit; end

  def update
    return unless @user.id == current_user.id || current_user.administrador?

    if @user.update(user_params)
      redirect_to users_path, notice: "Usuário #{@user.full_name || @user.email} atualizado com sucesso."
    else
      render :edit, alert: 'Ops, ocorreu um erro.'
    end
  end

  def become_admin
    current_user.become_admin

    redirect_to users_path, notice: 'Agora você é um administrador'
  end

  private

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.required(:user).permit(:first_name, :last_name, :email, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Geral</title>
    <div class='mb-5 mt-3'>
      <h1>Geral</h1>
    </div>
  </head>
  <body>
    <div id="container">
      <div class="card mt-3 mb-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Total de Usuários</h5>
          <p class="card-text"><%= "#{@users.count}" %></p>
          <a><%= link_to 'Todos usúarios', users_path, class: 'btn btn-primary' %></a>
        </div>
      </div>
      <div class="card mt-3 mb-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Total de Produtos</h5>
          <p class="card-text"><%= "#{@materials.count}" %></p>
          <a><%= link_to 'Todos Produtos', materials_path, class: 'btn btn-primary' %></a>
        </div>
      </div>
      <div class="card mt-3 mb-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Movimentação de produto</h5>
          <p class="card-text"><%= "#{@logs.count}" %></p>
          <a><%= link_to 'Entrada/Saída de produto', material_logs_path, class: 'btn btn-primary mb-3' %></a>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Almox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class=" container-fluid flex-basis" style="position: fixed; bottom: 0; left: 0;" >
      <div class="row">
        <div class="col-2 p-0">
          <%= render 'shared/sidebar' %>
        </div>
        <div class="col-10">
        <% flash.each do |nome, mensagem| %>
          <%= content_tag :div, mensagem, class: nome %>
        <% end %>
        <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/material_logs/index.html.erb
<div class='mb-5 mt-3'>
  <h1>Movimentações de estoque</h1>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @logs.human_attribute_name(:movimentado_em) %></th>
      <th><%= @logs.human_attribute_name(:usuário) %></th>
      <th><%= @logs.human_attribute_name(:produto) %></th>
      <th><%= @logs.human_attribute_name(:quantidade) %></th>
      <th><%= @logs.human_attribute_name(:status) %></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody class="col-span-12">
    <% if @logs.any?%>
      <% @logs.each do |log| %>
        <tr>
          <td><%= log.created_at.strftime('%d/%m/%Y') %></td>
          <td><%= log.user.full_name || log.user.email %></td>
          <td><%= log.material.name %></td>
          <td><%= log.quantity %></td>
          <td><%= log.translate_status %></td>
          <td></td>
        </tr>
      <% end %>
    <% else %>
      <td> Sem movimentações por aqui.</td>
    <% end %>
  </tbody>
</table>

app/views/material_logs/show.html.erb
<div class='mb-5 mt-3'>
<h1>Movimentações de estoque</h1>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @logs.human_attribute_name(:movimentado_em) %></th>
      <th><%= @logs.human_attribute_name(:produto) %></th>
      <th><%= @logs.human_attribute_name(:quantidade) %></th>
      <th><%= @logs.human_attribute_name(:usuário) %></th>
      <th><%= @logs.human_attribute_name(:status) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.created_at.strftime('%d/%m/%Y') %></td>
        <td><%= log.material.name %></td>
        <td><%= log.quantity %></td>
        <td><%= log.user.full_name || log.user.email %></td>
        <td><%= log.translate_status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/materials/_form.html.erb
<%= simple_form_for @material, url: url, method: method do |f| %>
  <div class="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8 shadow bg-white rounded mb-5">
    <h1 class="text-xl">Produto</h1>
    <div class='form-group my-4'>
      <div class='sm:col-span-3 mt-3'>
        <%= f.label :nome %>
      </div>
      <div class='sm:col-span-3 mt-3'>
        <%= f.text_field :name %>
      </div>
      <div class='sm:col-span-3 mt-3'>
        <%= f.label :quantidade_de_entrada %>
      </div>
      <div class='sm:col-span-3 mt-3'>
        <%= f.text_field :quantity_entrance %>
      </div>
      <div class='sm:col-span-3 mt-3'>
        <%= f.label :quantidade_de_saída %>
      </div>
      <div class='sm:col-span-3 mt-3'>
        <%= f.text_field :quantity_exit %>
      </div>
    </div>
      <div class="col-9 float-right" >
        <%= f.button :submit, 'Salvar', class: 'btn btn-primary mb-3' %>
      </div>
  </div>
<% end %>

app/views/materials/edit.html.erb
<%= render 'form', url: material_path(@material), method: :put %>

app/views/materials/index.html.erb
<div class="mb-5 mt-3">
  <h1>Produtos</h1>

<div>
<% if current_user.administrador? %>
  <div style="float: right;">
    <%= link_to 'Inserir novo produto', new_material_path, class: 'btn btn-primary mr-3' %>
  </div>
<% end %>
</div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= @materials.human_attribute_name(:criado_em) %></th>
        <th><%= @materials.human_attribute_name(:nome) %></th>
        <th><%= @materials.human_attribute_name(:quantidade) %></th>
        <th colspan="5"></th>
      </tr>
    </thead>

    <tbody class="col-span-12">
    <% if @materials.any? %>
      <% @materials.each do |material| %>
        <tr>
          <td><%= material.created_at.strftime('%d/%m/%Y') %></td>
          <td><%= material.name || '-' %></td>
          <td><%= material.quantity %></td>
          <% if material.material_logs.present? %>
            <td><%= link_to 'Movimentações', material_material_logs_path(material) %></td>
          <% else %>
            <td align="center"> Sem movimentações </td>
          <% end %>
          <td><%= link_to 'Entrada/Saída', edit_material_path(material) %></td>
          <% unless material.material_logs.present? %>
            <td><%= link_to 'Apagar', material_path(material), method: :delete %></td>
          <% else %>
            <td></td>
          <% end %>
        </tr>
      <% end %>
    <% else%>
      <td> Sem materiais no estoque! </td>
    <% end %>
    </tbody>
  </table>
</div>

app/views/materials/new.html.erb
<%= render 'form', url: materials_path, method: :post %>

app/views/shared/_sidebar.html.erb
<div class="container-fluid h-100 p-0 mr-1">
  <div class="row flex-nowrap">
      <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark w-100 h-100">
          <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
              <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                  <span class="fs-5 d-none d-sm-inline">Menu</span>
              </a>
              <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                  <li class="nav-item">
                      <a href="#" class="nav-link align-middle px-0">
                      <i class="fs-4 bi-people"></i><span><%= link_to 'Geral', home_index_path, class: 'ms-1 d-none d-sm-inline' %></span> </a>
                      </a>
                  </li>
                  <li>
                    <i class="fs-4 bi-people"></i><span><%= link_to 'Produtos', materials_path, class: 'ms-1 d-none d-sm-inline' %></span> </a>
                  </li>
                  <li>
                    <i class="fs-4 bi-people"></i><span><%= link_to 'Usuários', users_path, class: 'ms-1 d-none d-sm-inline' %></span> </a>
                  </li>
                  <li>
                    <i class="fs-4 bi-people"></i><span><%= link_to 'Todas movimentações', material_logs_path, class: 'ms-1 d-none d-sm-inline' %></span> </a>
                  </li>
              </ul>
              <hr>
        <div class="dropdown pb-4">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
                <span class="d-none d-sm-inline mx-1"><%= "#{current_user.full_name || 'Sem nome'}" %></span>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                <li><%= link_to 'Configurações', edit_user_path(current_user), class: 'dropdown-item' %>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><%= link_to 'Deslogar', destroy_user_session_path, class: 'dropdown-item', method: :delete %>
            </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= simple_form_for @user, url: user_path, method: :put do |f| %>
  <form class="p-3 mt-3 col-10">
    <div class="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8 shadow bg-white rounded mb-5">
      <h1 class="text-xl">Editar Usuário</h1>
      <div class='form-group my-4'>
        <div class='sm:col-span-3 mt-3'>
          <%= f.label :Nome %>
          <% if current_user.administrador? %>
            <div class="float-right m-3", style="float: right;">
              <%= f.select :role, ['usuario', 'suporte', 'administrador'] %>
            </div>
          <% end %>
        </div>
        <div class='sm:col-span-3'>
          <%= f.text_field :first_name %>
        </div>
         <div class='sm:col-span-3 mt-3'>
          <%= f.label :Sobrenome %>
        </div>
        <div class='sm:col-span-3'>
          <%= f.text_field :last_name %>
        </div>
         <div class='sm:col-span-3 mt-3'>
          <%= f.label :Email %>
        </div>
        <div class='sm:col-span-3'>
          <%= f.text_field :email %>
        </div>
        <div>
          <%= f.button :submit, 'Salvar', class: 'btn btn-primary mt-3 mb-3' %>
        </div>
  </form>
<% end %>

app/views/users/index.html.erb
<div class='mb-5 mt-3'>
  <h1>Usuários</h1>
  <% unless current_user.administrador? || User.all.count > 1 %>
    <div align="right">
      <a><%= link_to 'Tornar administrador', become_admin_path, class: 'btn btn-primary', method: :patch %></a>
    </div>
  <% end %>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @users.human_attribute_name(:criado_em) %></th>
      <th><%= @users.human_attribute_name(:nome) %></th>
      <th><%= @users.human_attribute_name(:email) %></th>
      <th><%= @users.human_attribute_name(:função) %></th>
      <th><%= @users.human_attribute_name(:status) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.created_at.strftime('%d/%m/%Y') %></td>
        <td><%= user.full_name || '-' %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= user.translate_status %></td>
        <% if current_user.administrador? %>
          <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>